"""
Tests for black-bar detection, cropping, and blur-fill.

Uses a synthetic 1920x1080 PNG with black bars (480px each side, 960px content)
generated by generate_fixture.py.  If the fixture is missing, run:
    python tests/generate_fixture.py

Test categories:
1. Detection — pillarbox_content_bounds returns correct (left, right) bounds.
2. Crop — cropped frame has the expected dimensions and no black columns.
3. Blur-fill — output is 1920x1080 with no column having mean intensity 0.
"""
import sys
from pathlib import Path

import cv2
import numpy as np
# Ensure the project root is importable
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from scene_utils import pillarbox_content_bounds, is_black_column  # noqa: E402
from blur_fill import blur_fill_cropped_frame, blur_fill_frame  # noqa: E402
from config import BLACK_THRESHOLD, PILLAR_EDGE_WINDOW, OUTPUT_WIDTH, OUTPUT_HEIGHT  # noqa: E402

FIXTURES = Path(__file__).resolve().parent / "fixtures"
PILLARBOXED_IMG = FIXTURES / "pillarboxed_1920x1080.png"
FULLWIDTH_IMG = FIXTURES / "fullwidth_1920x1080.png"

# Expected geometry of the synthetic fixture (see generate_fixture.py)
FRAME_W = 1920
FRAME_H = 1080
BAR_WIDTH = 480
CONTENT_LEFT = BAR_WIDTH        # 480
CONTENT_RIGHT = FRAME_W - BAR_WIDTH  # 1440
CONTENT_WIDTH = CONTENT_RIGHT - CONTENT_LEFT  # 960


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load(path: Path) -> np.ndarray:
    img = cv2.imread(str(path))
    assert img is not None, f"Fixture not found: {path}.  Run: python tests/generate_fixture.py"
    return img


def column_means(frame: np.ndarray) -> np.ndarray:
    """Return per-column mean intensity (averaged across rows and channels)."""
    return frame.mean(axis=(0, 2))  # shape: (width,)


# ---------------------------------------------------------------------------
# 1. Detection tests
# ---------------------------------------------------------------------------

class TestPillarboxDetection:
    """pillarbox_content_bounds should find the content region accurately."""

    def test_detects_pillarboxed_frame(self):
        frame = _load(PILLARBOXED_IMG)
        bounds = pillarbox_content_bounds(frame)
        assert bounds is not None, "Should detect pillarbox"

    def test_bounds_match_expected(self):
        """The detected left/right should be close to the known content edges."""
        frame = _load(PILLARBOXED_IMG)
        x_left, x_right = pillarbox_content_bounds(frame)
        # Allow ±PILLAR_EDGE_WINDOW tolerance due to windowed averaging
        tolerance = PILLAR_EDGE_WINDOW + 1
        assert abs(x_left - CONTENT_LEFT) <= tolerance, (
            f"Left bound {x_left} too far from expected {CONTENT_LEFT}"
        )
        assert abs(x_right - CONTENT_RIGHT) <= tolerance, (
            f"Right bound {x_right} too far from expected {CONTENT_RIGHT}"
        )

    def test_left_bar_fully_excluded(self):
        """Content region must not include any fully-black column from the left bar."""
        frame = _load(PILLARBOXED_IMG)
        x_left, x_right = pillarbox_content_bounds(frame)
        content = frame[:, x_left:x_right, :]
        col_means = column_means(content)
        # Every column in the content region should have significant intensity
        assert col_means.min() > BLACK_THRESHOLD, (
            f"Column {col_means.argmin()} in content has mean {col_means.min():.1f} "
            f"<= {BLACK_THRESHOLD}; left black bar was not fully cropped"
        )

    def test_right_bar_fully_excluded(self):
        """Content region must not include any fully-black column from the right bar."""
        frame = _load(PILLARBOXED_IMG)
        x_left, x_right = pillarbox_content_bounds(frame)
        content = frame[:, x_left:x_right, :]
        col_means = column_means(content)
        # Last columns should also be non-black
        right_cols = col_means[-20:]
        assert right_cols.min() > BLACK_THRESHOLD, (
            f"Right edge of content has near-black columns; right bar not fully cropped"
        )

    def test_symmetric_bars_give_symmetric_bounds(self):
        """With equal-width bars, the detected content should be roughly centred."""
        frame = _load(PILLARBOXED_IMG)
        x_left, x_right = pillarbox_content_bounds(frame)
        center = (x_left + x_right) / 2
        tolerance = PILLAR_EDGE_WINDOW + 2
        assert abs(center - FRAME_W / 2) <= tolerance, (
            f"Content center {center} is not near frame center {FRAME_W / 2}"
        )

    def test_no_pillarbox_for_full_width(self):
        """A full-width frame (no black bars) should return None."""
        frame = _load(FULLWIDTH_IMG)
        bounds = pillarbox_content_bounds(frame)
        assert bounds is None, "Full-width frame should not be detected as pillarboxed"


# ---------------------------------------------------------------------------
# 2. Crop tests (using detected bounds directly on the frame)
# ---------------------------------------------------------------------------

class TestCrop:
    """Cropping with detected bounds should produce a clean content frame."""

    def test_cropped_dimensions(self):
        """Cropped frame height unchanged, width matches detected content."""
        frame = _load(PILLARBOXED_IMG)
        x_left, x_right = pillarbox_content_bounds(frame)
        cropped = frame[:, x_left:x_right, :]
        assert cropped.shape[0] == FRAME_H, "Height should be unchanged"
        assert cropped.shape[1] == x_right - x_left
        # Width should be close to the known content width
        tolerance = 2 * (PILLAR_EDGE_WINDOW + 1)
        assert abs(cropped.shape[1] - CONTENT_WIDTH) <= tolerance

    def test_cropped_has_no_black_columns(self):
        """No column in the cropped result should be fully black."""
        frame = _load(PILLARBOXED_IMG)
        x_left, x_right = pillarbox_content_bounds(frame)
        cropped = frame[:, x_left:x_right, :]
        col_means = column_means(cropped)
        assert col_means.min() > BLACK_THRESHOLD, (
            f"Cropped frame has a near-black column at index {col_means.argmin()} "
            f"with mean {col_means.min():.1f}"
        )

    def test_cropped_content_preserved(self):
        """The cropped region should contain the same pixel data as the original content."""
        frame = _load(PILLARBOXED_IMG)
        x_left, x_right = pillarbox_content_bounds(frame)
        cropped = frame[:, x_left:x_right, :]
        # The fixture has content from CONTENT_LEFT to CONTENT_RIGHT.
        # The cropped region should overlap with that.
        # Pick a column well inside the content area and verify pixels match.
        mid = CONTENT_WIDTH // 2
        src_col = CONTENT_LEFT + mid
        if x_left <= src_col < x_right:
            dst_col = src_col - x_left
            np.testing.assert_array_equal(
                cropped[:, dst_col, :],
                frame[:, src_col, :],
            )


# ---------------------------------------------------------------------------
# 3. Blur-fill tests
# ---------------------------------------------------------------------------

class TestBlurFill:
    """blur_fill_cropped_frame should produce 1920x1080 with no black columns."""

    def test_output_dimensions(self):
        frame = _load(PILLARBOXED_IMG)
        x_left, x_right = pillarbox_content_bounds(frame)
        cropped = frame[:, x_left:x_right, :]
        filled = blur_fill_cropped_frame(cropped)
        assert filled.shape == (OUTPUT_HEIGHT, OUTPUT_WIDTH, 3)

    def test_no_black_columns_in_output(self):
        """After blur-fill, every column should have non-zero mean (blurred background, not black)."""
        frame = _load(PILLARBOXED_IMG)
        x_left, x_right = pillarbox_content_bounds(frame)
        cropped = frame[:, x_left:x_right, :]
        filled = blur_fill_cropped_frame(cropped)
        col_means = column_means(filled)
        # No column should be black (mean 0)
        assert col_means.min() > 0, (
            f"Column {col_means.argmin()} has mean 0 in blur-filled output"
        )
        # Stronger: no column should be near-black (the blur should spread color everywhere)
        assert col_means.min() > 5, (
            f"Column {col_means.argmin()} has very low mean {col_means.min():.1f} "
            f"in blur-filled output"
        )

    def test_edges_are_blurred(self):
        """The edge regions (blur background) should have lower high-frequency energy
        than the center region (sharp content), verified via Laplacian variance."""
        frame = _load(PILLARBOXED_IMG)
        x_left, x_right = pillarbox_content_bounds(frame)
        cropped = frame[:, x_left:x_right, :]
        filled = blur_fill_cropped_frame(cropped)
        gray = cv2.cvtColor(filled, cv2.COLOR_BGR2GRAY)
        lap = cv2.Laplacian(gray, cv2.CV_64F)

        center_var = lap[:, OUTPUT_WIDTH // 4 : 3 * OUTPUT_WIDTH // 4].var()
        left_edge_var = lap[:, :100].var()
        right_edge_var = lap[:, -100:].var()
        edge_var = (left_edge_var + right_edge_var) / 2

        assert center_var > edge_var, (
            f"Center Laplacian variance ({center_var:.2f}) should exceed "
            f"edge variance ({edge_var:.2f}); edges should be blurred"
        )

    def test_blur_fill_frame_direct(self):
        """blur_fill_frame (takes raw pillarboxed frame) should also produce valid output."""
        frame = _load(PILLARBOXED_IMG)
        filled = blur_fill_frame(frame)
        assert filled.shape == (OUTPUT_HEIGHT, OUTPUT_WIDTH, 3)
        col_means = column_means(filled)
        assert col_means.min() > 0, "No column should be pure black"

    def test_no_black_rows_in_output(self):
        """No row in the blur-filled output should be fully black either."""
        frame = _load(PILLARBOXED_IMG)
        x_left, x_right = pillarbox_content_bounds(frame)
        cropped = frame[:, x_left:x_right, :]
        filled = blur_fill_cropped_frame(cropped)
        row_means = filled.mean(axis=(1, 2))  # per-row mean
        assert row_means.min() > 0, (
            f"Row {row_means.argmin()} has mean 0 in blur-filled output"
        )


# ---------------------------------------------------------------------------
# 4. is_black_column helper tests
# ---------------------------------------------------------------------------

class TestIsBlackColumn:
    """Unit tests for the windowed is_black_column helper."""

    def test_pure_black_column(self):
        frame = np.zeros((100, 200, 3), dtype=np.uint8)
        assert is_black_column(frame, 50)

    def test_bright_column(self):
        frame = np.full((100, 200, 3), 200, dtype=np.uint8)
        assert not is_black_column(frame, 50)

    def test_mixed_frame_black_region(self):
        frame = np.full((100, 200, 3), 200, dtype=np.uint8)
        # Make columns 0-49 black
        frame[:, :50, :] = 0
        # Column 10 is deep inside black region, should be black
        assert is_black_column(frame, 10, window=5)

    def test_mixed_frame_bright_region(self):
        frame = np.full((100, 200, 3), 200, dtype=np.uint8)
        frame[:, :50, :] = 0
        # Column 150 is deep inside bright region
        assert not is_black_column(frame, 150, window=5)


# ---------------------------------------------------------------------------
# 5. Edge-case detection tests with synthetic frames
# ---------------------------------------------------------------------------

class TestEdgeCases:
    """Edge cases for pillarbox_content_bounds with various bar widths."""

    def _make_frame(self, w, h, left_bar, right_bar, content_val=200):
        """Create a frame with specified bar widths."""
        frame = np.zeros((h, w, 3), dtype=np.uint8)
        frame[:, left_bar:w - right_bar, :] = content_val
        return frame

    def test_wide_bars_detected(self):
        """Bars wider than min_bar should be fully detected, not truncated at min_bar."""
        frame = self._make_frame(1920, 1080, left_bar=400, right_bar=400)
        bounds = pillarbox_content_bounds(frame)
        assert bounds is not None
        x_left, x_right = bounds
        tolerance = PILLAR_EDGE_WINDOW + 1
        assert abs(x_left - 400) <= tolerance, f"Left bound {x_left} should be near 400"
        assert abs(x_right - 1520) <= tolerance, f"Right bound {x_right} should be near 1520"

    def test_asymmetric_bars(self):
        """Asymmetric bars: wider left bar than right bar."""
        frame = self._make_frame(1920, 1080, left_bar=500, right_bar=200)
        bounds = pillarbox_content_bounds(frame)
        assert bounds is not None
        x_left, x_right = bounds
        tolerance = PILLAR_EDGE_WINDOW + 1
        assert abs(x_left - 500) <= tolerance, f"Left bound {x_left} should be near 500"
        assert abs(x_right - 1720) <= tolerance, f"Right bound {x_right} should be near 1720"

    def test_very_narrow_bars_rejected(self):
        """Bars thinner than min_bar (5% of width) should not trigger detection."""
        # min_bar for 1920 = 96. Use 50px bars — too thin.
        frame = self._make_frame(1920, 1080, left_bar=50, right_bar=50)
        bounds = pillarbox_content_bounds(frame)
        assert bounds is None, "Bars thinner than PILLAR_MIN_WIDTH_RATIO should be rejected"

    def test_all_black_frame(self):
        """A fully black frame should return None (no content to detect)."""
        frame = np.zeros((1080, 1920, 3), dtype=np.uint8)
        bounds = pillarbox_content_bounds(frame)
        assert bounds is None

    def test_left_bar_only(self):
        """Only a left bar (no right bar) should return None (requires both bars)."""
        frame = np.full((1080, 1920, 3), 150, dtype=np.uint8)
        frame[:, :400, :] = 0  # left bar only
        bounds = pillarbox_content_bounds(frame)
        assert bounds is None, "Should require both bars"

    def test_right_bar_only(self):
        """Only a right bar (no left bar) should return None."""
        frame = np.full((1080, 1920, 3), 150, dtype=np.uint8)
        frame[:, 1520:, :] = 0  # right bar only
        bounds = pillarbox_content_bounds(frame)
        assert bounds is None, "Should require both bars"
